_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 41
                - 105
            "2":
                - 1
                - 41
                - 105
            "3":
                - 16
                - 55
            "4": 3.11.13
            "5": 0.20.1
            "8":
                - 1
                - 12
            "12": 0.20.1
            "13": linux-x86_64
batch_size:
    value: 64
criterion:
    value: cross_entropy
epochs:
    value: 5
freeze_backbone:
    value: true
learning_rate:
    value: 0.001
model:
    value: resnet18
optimizer:
    value: adam
